[package]
name = "sliproad"
version = "0.1.0"
authors = ["Gabriel Simmer"]
edition = "2018"

[dependencies]
actix-web = "3"
serde_json = "1.0"
toml = "0.4.2"
serde = { version = "1.0", features = ["derive"] }